Task 1
ancavar/formal-lang-course pull request #1
Opened 2024-09-08 15:42 UTC by ancavar

2024-09-11 14:33 UTC, vadyushkins requested changes

2024-09-11 14:33 UTC, vivalerievich commented on tests/test_task1.py
> +    graph = nx.nx_pydot.from_pydot(pydot_graph)
У вас должны быть файлы с ожидаемым содержимым, а вы тут одну и ту же функцию два раза вызываете и, конечно, получаете одно и то же

2024-09-12 00:14 UTC, ancavar commented on tests/test_task1.py
> +    graph = nx.nx_pydot.from_pydot(pydot_graph)
согласен, ерунда, поменял.........

2024-09-17 13:35 UTC, vadyushkins approved these changes

2024-09-17 14:05 UTC, merged